name: Run tests
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: info
        run: echo "💡 start ${{ github.workflow }}, event:${{ github.event_name }}, os:${{ runner.os }}, repo:${{ github.repository }}, branch:${{ github.ref }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: install dependencies
        run: npm ci
      - name: run the test
        run: export NODE_OPTIONS="--max-old-space-size=8192" npm t
      - name: delete draft releases from github
        uses: hugo19941994/delete-draft-releases@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: semantic release
        run: npm run release -ws --if-preset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: link local dependencies
        run: npm run task link && npm i --package-lock-only
      - name: push changes after running the task link
        # set husky to be executable
        # https://stackoverflow.com/questions/8598639/why-is-my-git-pre-commit-hook-not-executable-by-default#comment88478230_47166916
        run: |
          chmod +x .husky/pre-commit
          git config user.name ${{ github.actor }}
          git config user.email "${{ github.actor }}@github.com"
          git add . 
          git commit -m 'build: run task link' 
          git push
      - run: echo "💡 job status:${{ job.status }}."
